Arm
bennowotny/ECE453_DumptruckUltra pull request #21
Opened 2023-04-24 01:43 UTC by paulpak58

2023-04-24 18:09 UTC, abishekkannan23 commented on Software/DumptruckUltra-MCU/hw/arm/Arm/Arm.ino
Do we want/need to merge any of the .ino files into main?

2023-04-24 18:40 UTC, abishekkannan23 commented on Software/DumptruckUltra-MCU/hw/arm/arm.cpp
> +    void initServos(){
Optional: Could use Servo class for initialization

2023-05-01 14:51 UTC, bennowotny requested changes
Can we switch to using the header file from feature/arm-mcu?

2023-05-01 14:51 UTC, bennowotny commented on Software/DumptruckUltra-MCU/hw/arm/arm.hpp
Is this using the predefined header in feature/arm-mcu?  Could that be refactored to avoid more extensive refactoring in the FSM?

2023-05-01 15:28 UTC, paulpak58 commented on Software/DumptruckUltra-MCU/hw/arm/arm.hpp
This was a miscommunication on our part. Changing the header would take some time since all the methods are already dependent upon it, but I'd be willing to sit down for a bit today to make a unified header

2023-05-01 21:36 UTC, bennowotny approved these changes

2023-05-01 21:38 UTC, merged